services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    networks:
      - doris-net

networks:
  doris-net:
    external: true
    name: doris-opentelemetry-demo
